# Generated by Django 5.2.6 on 2025-10-25 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_kanbans(apps, schema_editor):
    """
    Cria um Kanban padrão para cada usuário que possui colunas.
    Se não houver usuários, cria um usuário admin padrão.
    """
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Kanban = apps.get_model('api', 'Kanban')
    KanbanColumn = apps.get_model('api', 'KanbanColumn')
    
    # Verifica se existem colunas
    if not KanbanColumn.objects.exists():
        return
    
    # Verifica se existe pelo menos um usuário
    if not User.objects.exists():
        # Cria um usuário admin padrão
        user = User.objects.create_superuser(
            username='admin',
            email='admin@example.com',
            password='admin123'
        )
    else:
        # Pega o primeiro usuário disponível
        user = User.objects.first()
    
    # Cria um Kanban padrão
    kanban = Kanban.objects.create(
        nome='Kanban Principal',
        descricao='Kanban criado automaticamente durante a migração',
        owner=user
    )
    
    # Associa todas as colunas existentes a este Kanban
    KanbanColumn.objects.update(kanban=kanban)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_kanbancolumn_kanbancard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbancolumn',
            options={'ordering': ['kanban', 'order', 'id'], 'verbose_name': 'Coluna do Kanban', 'verbose_name_plural': 'Colunas do Kanban'},
        ),
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanbans_owned', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Kanban',
                'verbose_name_plural': 'Kanbans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='kanbancolumn',
            name='kanban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='api.kanban'),
        ),
        migrations.RunPython(create_default_kanbans, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='kanbancolumn',
            name='kanban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='api.kanban'),
        ),
        migrations.CreateModel(
            name='KanbanShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_editar', models.BooleanField(default=False, help_text='Se True, o usuário pode editar o Kanban. Se False, apenas visualizar.')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('kanban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.kanban')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanbans_shared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compartilhamento de Kanban',
                'verbose_name_plural': 'Compartilhamentos de Kanban',
                'ordering': ['-shared_at'],
                'unique_together': {('kanban', 'usuario')},
            },
        ),
    ]
