# Generated by Django 5.2.6 on 2025-10-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_kanbancolumn_options_kanban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanban',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente associado a este Kanban (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanbans', to='api.client', verbose_name='Cliente'),
        ),
    ]
