services:
  db:
    image: postgres:16-alpine
    container_name: erp_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-erpdb}
      - POSTGRES_USER=${POSTGRES_USER:-erpuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-erppassword}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
