# Generated by Django 5.2.4 on 2025-12-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$Uagt23AnU7xsxeLbRYDsW9$uarXJLBE+SC1Vx2ks13vtXd9TUTqNGsV6yZRh8P0JvM=', max_length=128),
        ),
    ]
