# Generated by Django 5.2.4 on 2025-12-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$kFhOksETerUaohyMKBmCUI$szj675CRT4R/3qZXX4q7Psp3wxuv0AyBa55NVCTFf4A=', max_length=128),
        ),
    ]
