# Generated by Django 5.2.4 on 2025-12-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$WJxPKiH5lUk8bzfLLccMmW$qqZc5wYXx0PkvsJmarl0zudjtBPNHyFlXzc6ahuQYk0=', max_length=128),
        ),
    ]
