# Generated by Django 5.2.4 on 2025-12-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$obD9peTW6evYsNe80LKwGH$HxKP6nFCxQhZYetCB2uHFvZRPFfzf7c6BrAf3AmMgfA=', max_length=128),
        ),
    ]
