# Generated by Django 5.2.4 on 2025-12-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$krkJKv0Ssj1qH5lRQpmhVj$WFwCa8MCwwHBPpYXIgJVixqQlOec7j/UkOt7LLmx2qw=', max_length=128),
        ),
    ]
