# Generated by Django 5.2.4 on 2025-12-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_apresentacao_relatorio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Apresentação Relatório'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_bloqueio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Bloqueio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='parceiro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Parceiro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='relatorio_gerado',
            field=models.BooleanField(default=False, verbose_name='Relatório Gerado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='reuniao_apresentacao_agendada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reunião Apresentação Agendada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$FAJjyyypsjfKe3xEeM0YPq$etSi5YLfkE8gn3is6d2DdYxhsHMEeg4J99MPy3bt5K8=', max_length=128),
        ),
    ]
