# Generated by Django 5.2.4 on 2025-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$5g7PJ3soDkOuvTAz04BmD7$hahJ49zpe6sID8F2FkGxETtiKkTcfJIZBtWRIyFS2dk=', max_length=128),
        ),
    ]
