# Generated by Django 5.2.4 on 2025-12-14 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_cliente_cnpj_cliente_contato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Coluna')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('cor', models.CharField(default='#3B82F6', help_text='Cor em hexadecimal (ex: #3B82F6)', max_length=7, verbose_name='Cor')),
                ('limite_cards', models.IntegerField(blank=True, help_text='Limite máximo de cards nesta coluna', null=True, verbose_name='Limite de Cards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coluna',
                'verbose_name_plural': 'Colunas',
                'db_table': 'kanban_coluna',
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$ou3oqaGw3PxKO6h5n69TmV$LZNoNFk0suzGM4LH3yDP7rhcNzLT8yC99HW6+b2eIvU=', max_length=128),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridade')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Movimentação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_kanban', to='mi_app.cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_kanban', to='mi_app.produto', verbose_name='Produto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='mi_app.coluna', verbose_name='Coluna')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'kanban_card',
                'ordering': ['ordem', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='mi_app.card', verbose_name='Card')),
                ('coluna_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='mi_app.coluna', verbose_name='Coluna Destino')),
                ('coluna_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='mi_app.coluna', verbose_name='Coluna Origem')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Movimentação',
                'verbose_name_plural': 'Históricos de Movimentação',
                'db_table': 'kanban_historico_movimentacao',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Quadro')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanbans_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Quadro Kanban',
                'verbose_name_plural': 'Quadros Kanban',
                'db_table': 'kanban',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='coluna',
            name='kanban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='mi_app.kanban', verbose_name='Quadro'),
        ),
        migrations.CreateModel(
            name='RegraAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Regra')),
                ('tipo_trigger', models.CharField(choices=[('movimentacao', 'Movimentação de Card'), ('prazo', 'Prazo de Vencimento'), ('criacao', 'Criação de Card'), ('atribuicao', 'Atribuição de Responsável')], max_length=20, verbose_name='Tipo de Gatilho')),
                ('dias_antes_vencimento', models.IntegerField(blank=True, help_text='Para trigger de prazo: quantos dias antes notificar', null=True, verbose_name='Dias Antes do Vencimento')),
                ('acao_whatsapp', models.CharField(choices=[('cliente', 'Notificar Cliente'), ('responsavel', 'Notificar Responsável'), ('admin', 'Notificar Administrador')], max_length=20, verbose_name='Ação WhatsApp')),
                ('template_mensagem', models.TextField(help_text='Use {cliente_nome}, {produto_nome}, {card_titulo}, {responsavel_nome}, {data_vencimento}, {coluna_nome}', verbose_name='Template da Mensagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coluna_trigger', models.ForeignKey(blank=True, help_text='Coluna específica que ativa a regra (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.coluna', verbose_name='Coluna Gatilho')),
                ('kanban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_automacao', to='mi_app.kanban', verbose_name='Quadro')),
            ],
            options={
                'verbose_name': 'Regra de Automação',
                'verbose_name_plural': 'Regras de Automação',
                'db_table': 'kanban_regra_automacao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LogNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(help_text='Número de telefone do destinatário', max_length=20, verbose_name='Destinatário')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('erro', 'Erro'), ('pendente', 'Pendente')], default='pendente', max_length=10, verbose_name='Status')),
                ('erro_mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Envio')),
                ('tentativas', models.IntegerField(default=0, verbose_name='Tentativas')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='mi_app.card', verbose_name='Card')),
                ('regra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.regraautomacao', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'db_table': 'kanban_log_notificacao',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='coluna',
            unique_together={('kanban', 'ordem')},
        ),
    ]
