# Generated by Django 5.2.4 on 2025-12-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_coluna_alter_usuario_password_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanban',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kanbans', to='mi_app.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$SWogpoGZabQUHYHxYrYbop$SCH1UwIazxlSfA/gaIISmxCu4Xlaf8DXfDo9wOmq2aQ=', max_length=128),
        ),
    ]
