# Generated by Django 5.2.4 on 2025-12-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_kanban_cliente_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='mi_app.cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$JivHsFHQfvDmhC1Aj8WqrH$JIJkDvD3ikUyV2uS+6OBIIgaiGUuqUJjl3kv0yX+iY0=', max_length=128),
        ),
    ]
